alloy-rs/chains

- src/named.rs
companion for https://github.com/gakonst/ethers-rs/pull/2680
> chore: add metis as known legacy

- src/named.rs
polygon and mumbai support shanghai starting 29th 
closes #15
> feat: shanghai support for polygon

- .gitattributes
- CHANGELOG.md
- Cargo.toml
- assets/chains.json
- assets/chains.schema.json
- src/lib.rs
- src/named.rs
- src/spec.rs
Automatically-generated JSON bindings and specification
> feat: JSON bindings

- assets/chains.json
- src/named.rs
companion for https://github.com/gakonst/ethers-rs/pull/2710
> feat: add viction chain

- assets/chains.json
- src/named.rs
Adds the [Public Goods Network](https://publicgoods.network/) Mainnet and Sepolia testnet to chains.
> feat: add public goods network and pgn sepolia to chainsˆ

- src/named.rs
https://github.com/ethereum/discv4-dns-lists
> chore: add holesky to dns match

- assets/chains.json
- src/chain.rs
- src/named.rs
Adding Mode Network mainnet & testnet
Mainnet: https://docs.mode.network/mode-developer-mainnet/mode-dev-mainnet-information
Testnet: https://docs.mode.network/mode-testnet/using-mode-testnet
> feat: Add Mode & Mode Sepolia

- assets/chains.json
- src/chain.rs
- src/named.rs
Ralated to https://github.com/gakonst/ethers-rs/pull/2723
> feat(amoy): add amoy to chain config

- src/spec.rs
spec tests require some features
> chore: update cargo t note for spec

- assets/chains.json
- src/chain.rs
- src/named.rs
Added Syndr L3 Sepolia to chain config
> Feat: Add Syndr Sepolia L3

- assets/chains.json
- src/chain.rs
- src/named.rs
Added `Linea` and `LineaGoerli` serde kebab cases aliases, tests and return functions for aliases.
> Add 'Linea' and 'LineaGoerli' serde kebab cases aliases

- assets/chains.json
- src/named.rs
> feat: update Scroll chain currency symbol and shanghai readiness

- assets/chains.json
- src/chain.rs
- src/named.rs
This change adds Degen mainnet chain
> feat: add degen chain

- src/chain.rs
1. add an function to return optimism sepolia;
2. adjust the order of define the mainnet,testnet chains
> feat(chain): add method optimism_mainnet

- assets/chains.json
- src/named.rs
https://github.com/foundry-rs/foundry/issues/7733
> fix: correct amoy endpoint

- assets/chains.json
- src/named.rs
> fix: correct Arbiturm blocktime hint 

- assets/chains.json
- src/chain.rs
- src/named.rs
Adds Ronin mainnet
Source: https://docs.roninchain.com/validators/setup/parameters/mainnet
Closes https://github.com/alloy-rs/chains/issues/65
> feat: add Ronin mainnet

- src/named.rs
> chore: fix fmt

- assets/chains.json
- src/chain.rs
- src/named.rs
- **Add darwinia crab koi network**
> feat: add darwinia crab koi

- assets/chains.json
- src/named.rs
Following #53, this PR adds the support for Etherlink Mainnet.
Thanks!
> feat(Chains): add Etherlink mainnet

- assets/chains.json
- src/named.rs
https://gravity.xyz
chain list:
- https://chainlist.org/chain/1625
- https://chainlist.org/chain/13505
social:
- https://x.com/GravityChain
> feat: add gravity alpha mainnet and sepolia testnet

- src/chain.rs
> feat: add is_ethereum

- assets/chains.json
- src/named.rs
**Changes made:**
- Updates zksync testnet chainID to be accurate, see: https://docs.zksync.io/build/connect-to-zksync#sepolia-testnet-network-details
> fix: update zksync testnet chainID

- assets/chains.json
- src/named.rs
Metis links to routescan on their official docs https://www.metis.io/developers as andromeda explorer is very unreliable.
> fix: update explorer

- assets/chains.json
- src/named.rs
Adding Soneium Minato Testnet - https://docs.soneium.org/docs/builders/overview
> feat: add soneium minato testnet

- assets/chains.json
- src/named.rs
https://worldcoin.notion.site/World-Chain-Developer-Preview-Guide-23c94a67683f4e71986e5303ab88c9f3
> feat: add world

- assets/chains.json
- src/named.rs
> feat: add iotex

- assets/chains.json
- src/named.rs
reference: https://docs.unichain.org/docs/technical-information/network-information
> chore: add Unichain Sepolia Testnet

- assets/chains.json
- src/named.rs
- core: https://scan.coredao.org
- merlin: https://scan.merlinchain.io
- bitlayer: https://www.btrscan.com
> add core, merlin, bitlayer

- assets/chains.json
- src/named.rs
Reference: https://docs.apechain.com/metamask , https://apescan.io/
> Add ApeChain and Curtis Testnet

- assets/chains.json
- src/named.rs
https://docs.soniclabs.com/sonic/testnet/getting-started
> feat: add sonic testnet

- src/chain.rs
add scroll function:
* `pub const fn scroll_mainnet() -> Self {`
* `pub const fn scroll_sepolia() -> Self {`
> add scroll function

- src/chain.rs
- src/named.rs
Defining Ink mainnet network information and explorer urls
> Adding in Ink Mainnet information

- assets/chains.json
- src/named.rs
> feat: add happychain testnet

- assets/chains.json
- src/named.rs
Bera doc https://docs.berachain.com/
Bera github: https://github.com/berachain
FYI: cartio is the last testnet it's like a pre-mainnet
> feat: added berachain

- assets/chains.json
- src/named.rs
Sorry guys, in the previus PR one of the chains I sent is not correct (BerachainCartio)
> fix: berachain chain information

- assets/chains.json
- src/named.rs
> feat: add sonic mainnet

- src/chain.rs
Adding fn's for https://github.com/paradigmxyz/reth/pull/14483
> feat: add methods for Unichain mainnet and sepolia

- assets/chains.json
- src/named.rs
add Hyperliquid chain and remove Zora Goerli Testnet configuration
> chore: add hyperliquid

- assets/chains.json
- src/named.rs
Staying as draft until the chainid is official
> feat: add hoodi

- assets/chains.json
- src/chain.rs
- src/named.rs
- add berachain functions to chain.rs
- add berachain bepolia to named.rs
> feat: update berachain bepolia

- assets/chains.json
- src/chain.rs
- src/named.rs
https://docs.etherscan.io/hoodi-etherscan
> feat: Etherscan URLs for Hoodi

- assets/chains.json
- src/chain.rs
- src/named.rs
- add sonic functions to chain.rs
- add sonic blaze to named.rs
- update instructions with cargo formatting
> feat: update sonic blaze

- Cargo.toml
> chore(deps): primitives 1.0

- assets/chains.json
- src/chain.rs
- src/named.rs
- Adds a few Elastic Network chains and their configurations (abstract, lens, sophon)
> feat: introduces elastic network named chains

- assets/chains.json
- src/named.rs
Apologies missed the instructions in readme, was only referencing a previous PR. Let me know if this update is in the right direction!
> Add Hyperevmscan.io

- assets/chains.json
- src/named.rs
Add [fluent](https://www.fluent.xyz/)
> Adds fluent devnet and testnet

- src/chain.rs
- src/named.rs
We've had a breaking release since.
> chore: remove deprecated functions

- src/named.rs
we have hoodi etherscan here now
> chore: remove hoodi etherscan todo

- assets/chains.json
- src/named.rs
Adds the [Signet Pecorino testnet](https://signet.sh/docs/learn-about-signet/simplifying-the-rollup/).
> feat(chains): add signet pecorino testnet
