alloy-rs/chains

src/lib.rs
src/named.rs

In preparation for porting `enum Chain { Named(NamedChain), Id(u64) }` from Reth/Foundry.

chore: rename Chain to NamedChain

---

Cargo.toml
src/chain.rs
src/lib.rs
src/named.rs

https://github.com/paradigmxyz/reth/blob/2bd8c7e7e62594fc82fcf1fa50bc56601d3489f6/crates/primitives/src/chain/mod.rs#L97

feat: port Chain from Reth

---

src/chain.rs
src/lib.rs

Instead of checking whether `Self::Id(_)` can be converted into a `NamedChain` everywhere, we can enforce this at construction by making `Chain` a struct with a hidden inner `ChainKind` enum.
By making the fields private, we also make room for potential optimizations in the future, such as reducing the size of `Chain` from 16 to 8 bytes.

feat: split Chain into a struct and ChainKind enum

---

src/named.rs

chore: add zora

---

src/named.rs

Update the op-stack chains to return a blocktime hint of 2 seconds.
The following chains are all op-stack:
- `Optimism`
- `OptimismGoerli`
- `OptimismSepolia`
- `Base`
- `BaseGoerli`
- `Zora`
- `ZoraGoerli`
- `ZoraSepolia`

chains: op-stack chains at 2 seconds

---

src/chain.rs
src/named.rs

this pr introduce to get_block_explorer_url to found block explorer URl and convert_to_name_cain to convert id to blockchain name and added is_testnet in NamedChain

New utility method

---

assets/chains.json
src/named.rs

no trailing `/` on all etherscan urls

chore: unify etherscan url format

---

assets/chains.json
src/chain.rs
src/named.rs

add base sepolia https://docs.base.org/using-base/

feat: add base sepolia

---

assets/chains.json
src/chain.rs
src/named.rs

- feat: add blast sepolia
Added Blast Sepolia support using https://docs.blast.io/using-blast & https://testnet.blastscan.io/documentation/recipes/foundry-verification.

Feat: Add blast sepolia

---

assets/chains.json
src/named.rs

This Pr adds support for[ Kakarot zkEVM's](https://kakarot.org/) upcoming sepolia testnet, the PRs for the same have already been merged in [viem](https://github.com/wevm/viem/blob/main/src/chains/definitions/kakarotSepolia.ts) and [ethereum-lists/chains](https://github.com/ethereum-lists/chains/blob/a723229a31400c6ed60538a582acebbe0cd6361c/_data/chains/eip155-107107114116.json#L2).

feat: add kakarot sepolia

---

assets/chains.json
src/named.rs

Updating api_url related to [Blastscan API docs](https://blastscan.io/apis#accounts)

fix: correct blast api url

---

assets/chains.json
src/named.rs

:wave: this PR is here to add the support for Etherlink Testnet. Etherlink is a layer 2 blockchain EVM compatible with a well-established testnet already.
I’m not totally sure about the contributing guidelines to add new network, so I hope this PR does not come outside of a due process. If it is the case, please don’t hesitate to redirect me in the right direction!

feat(chain): Add Etherlink Testnet

---

assets/chains.json
src/named.rs

Currently this repo uses the Routescan URL's for verification with Blast Sepolia making it unable to verify contracts through Blastscan.
This PR updates them to properly use Etherscan (Blastscan) instead just as Blast mainnet does.

fix: correct Etherscan URLs for Blast Sepolia

---

assets/chains.json
src/named.rs

Use `amoy.polygonscan.com` as both explorer and verification endpoint
ref https://github.com/foundry-rs/foundry/issues/7922
ref https://github.com/foundry-rs/foundry/issues/7724

fix: update Amoy testnet endpoints

---

assets/chains.json
src/chain.rs
src/named.rs

👋 this PR is here to add the support for opBNB Mainnet/Testnet. opBNB is a layer 2 blockchain EVM compatible with a well-established already.
We are currently developing reth to support opBNB, so hope Chain Sepc can be added to the official repository.

feat(chain): add opBNB mainnet and testnet

---

assets/chains.json
src/chain.rs
src/named.rs

Adds Taiko mainnet and Taiko Hekla testnet
Currently, block time matches Ethereum's block time, but expected to decrease once Taiko moves to decentralized proposing / achieves preconfirmations

feat: add Taiko mainnet/testnet

---

assets/chains.json
src/named.rs

Adds Autonomys (formerly Subspace Network) Nova EVM [domain](https://academy.autonomys.net/subspace-protocol/decoupled-execution/domains/nova-evm). We are currently on a testnet but will be launching mainnet soon (will follow up with a different PR once we clear up chain IDs, etc.)

Add Autonomys Nova devnet

---

assets/chains.json
src/chain.rs
src/named.rs

Adds support for shimmer network https://shimmer.network/
Marked as a legacy because of this issue: https://github.com/iotaledger/wasp/issues/3392

Shimmer network support

---

assets/chains.json
src/chain.rs
src/named.rs

Flare networks https://docs.flare.network/
Flare derives its codebase from Avalanche so it does not support Shanghai Fork, but they ported EIP-1559 support
Sidefix: moved shimmer into blockscout section

Flare network support

---

assets/chains.json
src/named.rs

Mark `AnvilHardhat` as shanghai compatible as it is launched with `latest` by default (`cancun`)
Closes https://github.com/foundry-rs/foundry/issues/8730
Related code in Foundry: https://github.com/foundry-rs/foundry/blob/44cceb4a3d0a64faf818f16ce7c6ab7dc3a27400/crates/script/src/execute.rs#L234-L259

Fix: `anvil` reports not supporting `EIP-3855` (Shanghai)

---

CHANGELOG.md
assets/chains.json
src/chain.rs
src/named.rs

PR to add Immutable zkEVM and Immutable zkEVM testnet.
The chain configuration is taken from here: https://docs.immutable.com/platform/zkevm/chain-config/
More information about Immutable can be found here: https://www.immutable.com/  and  https://x.com/Immutable

add: Immutable zkEVM and Immutable zkEVM testnet

---

src/named.rs

The original motivation for `as C` was from some blog post I can't find, I don't really like this anymore because an invalid chain would cause a warning for unreachable patterns which is caught by CI

chore: import enum with glob instead of as C

---

src/chain.rs
src/named.rs

This is a rebranding for BNB smart chain, the current name should be `BNB Smart Chain`.

chore: correct bnb smart chain name

---

assets/chains.json
src/named.rs

Updates network configuration for Kakarot's launch on Starknet Sepolia:
**Chain ID:** `1802203764` → `5424235787602241`
**Chain name:** `KakarotSepolia` → `KakarotStarknetSepolia`
**Network alias:** `kakarot-sepolia` → `kakarot-starknet-sepolia`
This PR updates all relevant references throughout the codebase.

Update Chain ID for Kakarot Sepolia

---

assets/chains.json
src/named.rs

This PR updates Kakarot starknet sepolia chain id from `5424235787602241` to `920637907288165`

update kakarot starknet sepolia

---

src/chain.rs
src/named.rs

Adds helper method to check if `NamedChain` belongs to the Arbitrum configuration

feat(`NamedChain`): is_arbitrum

---

assets/chains.json
src/named.rs

- Update Celo / CeloAlfajores with correct Etherscan URL
- Correctly identify `Celo Baklava` as using Blockscout

fix: update explorer API endpoint for `Celo` / `CeloAlfajores` to use Etherscan

---

assets/chains.json
src/named.rs

Updates the World Chain urls to use worldscan.org instead of explorer.alchemy.com.
Also removes the `nativeCurrencySymbol` for World Chain and World Chain Sepolia

Update World Chain urls

---

assets/chains.json
src/chain.rs
src/named.rs

Adds Treasure mainnet (61166) and Treasure Topaz testnet (978658).
`cargo test` runs locally.

feat: add treasure mainnet and topaz testnet

---

src/named.rs

Since hex-literal does not allow characters other than the usual hex digits, it is both erroneous and unnecessary to add the '0x' prefix.

Remove 0x prefix from hex literal string to fix build

---

Cargo.toml

chore(deps): bump alloy-primitives 0.8.18

---

src/chain.rs

supports `==` with both types on either side

feat: add inverse partialeq for chainid

---

assets/chains.json
src/named.rs

- Add berachain
- Fix: return values of etherscan_urls
- Fix: wrapped_native_token for sonic

add berachain

---

assets/chains.json
src/named.rs

Adding rootstock testnet chain in the list of available chains under `NamedChain` enum. 
We need it in foundry project to add a check related to Rootstock testnet. 
Following tests passed!
```
cargo test --all-features
cargo fmt --all
```

Add `Rootstock` testnet chain

---

assets/chains.json
src/named.rs

This PR updates etherscan api urls to v2 for v2 supported chains.
resolves https://github.com/alloy-rs/chains/issues/173
required for https://github.com/paradigmxyz/reth/issues/17142
see [Etherscan v2 API](https://docs.etherscan.io/etherscan-v2/v2-quickstart) & [v2 supported chains](https://docs.etherscan.io/etherscan-v2/supported-chains)
cc @mattsse

chore: update etherscan api urls to v2

---

assets/chains.json
src/named.rs

pretty sure these chains use `ETH` for the native token

chore: add base, optimism native token name

---

assets/chains.json
src/named.rs

There are a lot of URLs that are no longer active and instead of returning dead links we should return `None`. Note I did not remove any chains all together, only the links to the verification url and explorer url with the exception of Mantle Testnet which explorer now points to Mantle Sepolia: 
https://explorer.testnet.mantle.xyz/api redirects to https://explorer.sepolia.mantle.xyz/api
https://explorer.testnet.mantle.xyz redirects to https://sepolia.mantlescan.xyz
Etherscan has now fully deprecated their V1 API and this means some old testnet chains are not included in the V2 API like `Ropsten`, `Kovan`, `Rinkeby` and `Goerli`. A lot of their clients who hosted old testnets (basically anything not Sepolia) have been deprecated too.
See list here: …

chore: go through all verification API endpoints and deprecate / fix those that are down

---

assets/chains.json
src/chain.rs
src/named.rs

Update applied according to information on https://docs.soniclabs.com/sonic/build-on-sonic/getting-started
Closes #201 
Deprecated Sonic Blaze as it has no explorer URL available (just redirects to Sonic Testnet which has a different chain id)

fix: Sonic Blaze deprecated, Sonic Testnet chain id update, explorer URL update

---

assets/chains.json
src/named.rs

Per https://sepolia-faucet.kakarot.org/ the Sepolia Testnet has closed, the explorer URL and explorer API URL are down
Closes #199

chore: deprecate kakarot sepolia

---

assets/chains.json
src/named.rs

Closes #198 
Reorders list to be alphabetical for easier maintenance

fix: update Avalance URLs, now use Etherscan API key

---

assets/chains.json
src/named.rs

Follow up of https://github.com/alloy-rs/chains/pull/207, a nice to have
Can be included in the next release

fix: Katana now requires an `ETHERSCAN_API_KEY`
